// Everything the dashboard shows, in Dutch (tone: BOUWPLAN 1.12).
export const T = {
  appName: 'Hyper&Focus',
  nav: { today: 'Vandaag', projects: 'Projecten', parking: 'Parkeerplaats', settings: 'Instellingen' },
  /** Shorter labels for the bar at the bottom of a phone. */
  navShort: { today: 'Vandaag', projects: 'Projecten', parking: 'Parkeren', settings: 'Instellingen' },
  loading: 'Even laden.',
  error: 'Dat lukte niet. Probeer het zo opnieuw.',
  retry: 'Opnieuw',
  logout: 'Uitloggen',
  soon: 'Dit scherm komt in de volgende stap.',
  today: {
    count: { 0: 'Er staat niets open.', 1: 'Eén taak vandaag.', 2: 'Dit zijn je twee.', 3: 'Dit zijn je drie.' } as Record<number, string>,
    empty: 'Stuur in Telegram wat je wilt doen. Dan zet ik het klaar.',
    window: 'Focusvenster',
    moveWindow: 'Schuif venster',
    moveTo: 'Nieuwe begintijd',
    save: 'Opslaan',
    cancel: 'Annuleren',
    quickWin: 'Snelle winst',
    inWindow: 'In je venster',
    firstStep: 'Eerste stap',
    start: 'Start',
    done: 'Af',
    tomorrow: 'Morgen',
    howLong: 'Hoe lang?',
    started: 'Blok gestart. Het einde en de pitstop komen in Telegram.',
    blockRuns: 'Blok loopt tot',
    pitstopUntil: 'Pitstop tot',
    log: 'Vandaag gedaan',
    logEmpty: 'Nog leeg. Je eerste blok staat er straks.',
    min: 'min',
  },
} as const;
