// Everything the dashboard shows, in Dutch (tone: BOUWPLAN 1.12).
export const T = {
  appName: 'Hyper&Focus',
  nav: { today: 'Vandaag', projects: 'Projecten', parking: 'Parkeerplaats', settings: 'Instellingen' },
  /** Shorter labels for the bar at the bottom of a phone. */
  navShort: { today: 'Vandaag', projects: 'Projecten', parking: 'Parkeren', settings: 'Instellingen' },
  loading: 'Even laden.',
  error: 'Dat lukte niet. Probeer het zo opnieuw.',
  retry: 'Opnieuw',
  save: 'Opslaan',
  cancel: 'Annuleren',
  logout: 'Uitloggen',
  today: {
    count: { 0: 'Er staat niets open.', 1: 'Eén taak vandaag.', 2: 'Dit zijn je twee.', 3: 'Dit zijn je drie.' } as Record<number, string>,
    empty: 'Stuur in Telegram wat je wilt doen. Dan zet ik het klaar.',
    emptyWithAssistant: 'Schrijf bij de braindump op wat je wilt doen. Dan zet ik het klaar.',
    telegramHint: 'Of stuur in Telegram wat je wilt doen. Dan zet ik het klaar.',
    window: 'Focusvenster',
    moveWindow: 'Schuif venster',
    moveTo: 'Nieuwe begintijd',
    save: 'Opslaan',
    cancel: 'Annuleren',
    quickWin: 'Snelle winst',
    inWindow: 'In je venster',
    firstStep: 'Eerste stap',
    start: 'Start',
    done: 'Af',
    tomorrow: 'Morgen',
    howLong: 'Hoe lang?',
    started: 'Blok gestart. Het einde en de pitstop komen in Telegram.',
    blockRuns: 'Blok loopt tot',
    pitstopUntil: 'Pitstop tot',
    log: 'Vandaag gedaan',
    logEmpty: 'Nog leeg. Je eerste blok staat er straks.',
    min: 'min',
  },
  projects: {
    tabProjects: 'Projecten',
    tabClients: 'Klanten',
    newProject: 'Nieuw project',
    newClient: 'Nieuwe klant',
    newTask: 'Taak toevoegen',
    title: 'Titel',
    name: 'Naam',
    contact: 'Contactpersoon',
    notes: 'Notities',
    client: 'Klant',
    noClient: 'Geen klant',
    deadline: 'Deadline',
    dueDate: 'Datum',
    minutes: 'Duur',
    noMinutes: 'Weet ik nog niet',
    project: 'Project',
    priority: 'Prioriteit',
    priorities: { 1: 'Hoog', 2: 'Normaal', 3: 'Laag' },
    weeklyFocus: 'Weekfocus',
    paused: 'Gepauzeerd',
    pause: 'Pauzeer',
    resume: 'Weer actief',
    finish: 'Project af',
    park: 'Parkeren',
    edit: 'Bewerk',
    add: 'Toevoegen',
    noTasks: 'Geen open taken.',
    noProjects: 'Nog geen projecten.',
    noClients: 'Nog geen klanten.',
    projectCount: { 0: 'Geen projecten', 1: '1 project' } as Record<number, string>,
    projectsMany: 'projecten',
    tasksMany: 'taken',
    oneTask: '1 taak',
    min: 'min',
  },
  parking: {
    parked: 'Parkeerplaats',
    parkedIntro: 'Taken die even niet hoeven. Terughalen kan altijd.',
    parkedEmpty: 'Leeg. Niets staat geparkeerd.',
    unpark: 'Terughalen',
    release: 'Loslaten',
    releaseSure: 'Loslaten? Dan verdwijnt hij uit je lijsten.',
    ideas: 'Ideeënbak',
    ideasIntro: 'Ideeën komen nooit direct in je focus. Eén per week mag een project worden.',
    ideasEmpty: 'Leeg. Een idee schrijf je hierboven op.',
    newIdea: 'Nieuw idee',
    add: 'Opschrijven',
    promote: 'Maak project',
    promoted: 'is nu een project. Je vindt het bij Projecten.',
    promoteUsed: 'Deze week is er al een idee een project geworden. Volgende week kan er weer één.',
    archive: 'Archiveren',
    edit: 'Bewerk',
    min: 'min',
  },
  settings: {
    saved: 'Opgeslagen.',
    rhythm: 'Ritme',
    rhythmIntro: 'Wanneer werk je het best? Daar zet ik je focusvenster.',
    prefs: { morning: 'Ochtend', afternoon: 'Middag', evening: 'Avond', unknown: 'Weet ik niet' },
    ownStart: 'Eigen begintijd',
    length: 'Lengte van het venster',
    learned: 'Geleerd ritme',
    learnedIntro: 'Deze tijden heb je overgenomen na een weekreview.',
    workWeek: 'Werkweek',
    workDays: 'Werkdagen',
    workStart: 'Begin',
    workEnd: 'Einde',
    reviewOn: 'Je weekreview komt op',
    dayTimes: 'Dagtijden',
    morning: 'Ochtendbericht',
    midday: 'Bericht rond het middaguur',
    wrapup: 'Afsluiting van de dag',
    quiet: 'Stille uren',
    quietIntro: 'In deze uren stuur ik niets.',
    from: 'Van',
    to: 'Tot',
    rewards: 'Beloningen',
    rewardsIntro: 'De beloningsminuut na een blok. Blokken en pitstops lopen altijd door.',
    on: 'Aan',
    off: 'Uit',
    calendar: 'Agenda',
    calendarIntro: 'Met je agenda plan ik om je afspraken heen.',
    calendarOff: 'De agendakoppeling staat nog niet aan.',
    calendarNone: 'Geen agenda gekoppeld.',
    calendarLinked: 'Gekoppeld',
    connect: 'Agenda koppelen',
    connectNote: 'De koppelpagina opent in een nieuw venster. De link werkt 15 minuten.',
    disconnect: 'Ontkoppelen',
    headsUp: 'Seintje voor een afspraak',
    followup: 'Vraag na een afspraak',
    providers: { ics: 'ICS-link', google: 'Google Agenda', microsoft: 'Outlook', apple: 'Apple Agenda' } as Record<string, string>,
    tools: 'Tools',
    toolsIntro: 'Waar je werkt. Bij een taak zet ik de knop naar die plek klaar.',
    none: 'Niet ingesteld',
    choose: 'Kies een tool',
    ownLink: 'Eigen link',
    link: 'Link (https://)',
    remove: 'Verwijder',
    profile: 'Profiel',
    name: 'Naam',
    timezone: 'Tijdzone',
    data: 'Je gegevens',
    dataIntro: 'Download alles wat Hyper&Focus van je bewaart, of verwijder het.',
    export: 'Exporteer mijn gegevens',
    delete: 'Verwijder mijn gegevens',
    deleteWarn: 'Dit verwijdert je account, taken, projecten, ideeën, berichten en agendakoppeling. Terugzetten kan niet.',
    deleteType: 'Typ verwijder om te bevestigen',
    deleteWord: 'verwijder',
    deleteNow: 'Alles verwijderen',
    logout: 'Uitloggen',
    days: ['Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za', 'Zo'],
    dayNames: ['maandag', 'dinsdag', 'woensdag', 'donderdag', 'vrijdag', 'zaterdag', 'zondag'],
    min: 'min',
  },
  kiki: {
    open: 'Braindump',
    close: 'Sluiten',
    intro: 'Schrijf op wat er in je hoofd zit. Ik maak er taken, notities en ideeën van. Jij kiest wat erin gaat.',
    label: 'Wat zit er in je hoofd?',
    sort: 'Ordenen',
    sorting: 'Even ordenen…',
    kinds: { task: 'Taak', note: 'Notitie', idea: 'Idee' } as Record<string, string>,
    save: (n: number) => (n === 1 ? 'Sla 1 item op' : `Sla ${n} items op`),
    again: 'Opnieuw',
    saved: (n: number) => (n === 1 ? '1 item staat erin.' : `${n} items staan erin.`),
    failedSome: (n: number) => (n === 1 ? '1 item lukte niet. Zet het er in Telegram bij.' : `${n} items lukten niet. Zet ze er in Telegram bij.`),
    off: 'staat nog niet aan.',
    min: 'min',
    noMinutes: 'Duur',
  },
} as const;
